apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: arduino-website
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer  # Use NodePort or ClusterIP if LoadBalancer is not available
