apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: arduino-website
spec:
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer  # Use NodePort or ClusterIP if LoadBalancer is not available
